name: Build with Push to aws

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup dotnet 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      
      - name: Build project 
        run: |
          dotnet restore
          dotnet publish -o site

      - name: create zip package
        run: |
          cd site
          zip -r ../site.zip *

      - name: deploy to aws EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${AKIA6GBMBSV4HV2TS6YS}}
          aws_secret_key: ${{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}}
          application_name: Raknare API
          environment_name: RaknareAPI-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip
